name: Deploy Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      chartName:
        required: false
        default: ''
        type: string
      charts_path:
        required: false
        default: ''
        type: string

jobs:
  deploy:
    name: 'Update helm charts'
    #runs-on: buildjet-4vcpu-ubuntu-2204
    runs-on: ubuntu-latest
    env:
      HELM_OWNER: ixofoundation
      HELM_REPO: ixo-helm-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install Helm'
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Update helm chart
        uses: shini4i/helm-charts-updater@v1
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          gh_user: ${{ env.HELM_OWNER }}
          gh_repo: ${{ env.HELM_REPO }}
          chart_name: ${{ inputs.chartName != '' && inputs.chartName || github.repository }}
          app_version: ${{ inputs.version }}
          charts_path: ${{ inputs.charts_path != '' && inputs.charts_path || format('charts/{0}', inputs.environment) }}
          commit_author: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          update_chart_annotations: true